### ISSUE TITLE
Coinbase addresses from some blocks not logged

### ISSUE THREAD

**Issue by bigreddmachine** [dashpay/insight-api-dash#14]
I am working on some things using the bitcore and insight APIs and have set up insight-ui-dash, insight-api-dash, and bitcore-node-dash in an Ubuntu virtual machine on my laptop so that I don't abuse the explorer here: https://insight.dash.siampm.com/

Everything seems to have gone fine on install and the explorer ui and api both seem to be working nicely. However, as I've been building out methods, I encountered an issue that I can't resolve.

If I query the API for coinbase address histories, many addresses do not appear to have been indexed. This does not seem to be an issue for addresses with more than 1 block mined, such as those controlled by pools. The block explorer mentioned about on siampm.com does not seem to have this issue, so I was wondering if there is some kind of flag I need to tweak or patch to apply to fix my issue.

**Comment by nmarley** [comment]
Hi, I just spot-checked a sample coinbase TX, block 4138, info:

blockhash: 0000000031bf8aaba97392dc01b90efd5bc5d43b17b39a45d5e47a5cb662bbe6
txid: 1de286d64b6a379e910e70e6ac5e220b6952fdd952f7e4e2abe6ababb59dd12d
address: XvW5YcFFy4rrVpQfVW13yjo6SN7iKFHdF5

So, from this info (again, random spot-check), I don't see any issue here. Some of these that you found, you may have come across P2PK transactions instead (meaning, pay to pubkey instead of pubkey hash). In this case, a fix was applied a few months ago to include these into the address index. In any case, this seems to be working now.

Please re-open an issue if this is still a problem for you.
